# Generated by Django 4.2.9 on 2024-02-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('mark', models.FloatField()),
                ('isplaced', models.BooleanField(default=False)),
            ],
        ),
    ]
